title: Alexandre RAVICHANDRAN - Website
email: alexandre.ravichandran@gmail.com
description: >-
  Site de Alexandre RAVICHANDRAN, developpeur web back-end junior
domain: alexandreravichandran.github.io
url: "https://alexandreravichandran.github.io"
github_username:  AlexandreRavichandran

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
